version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Preparing build..."

  build:
    commands:
      - echo "Running build..."
      #- python your_script.py  # Optional: run your Python script
      - zip -r output.zip .    # Zip all files in the project folder

  post_build:
    commands:
      - echo "Zipping completed. Uploading to S3..."

artifacts:
  files:
    - output2.zip
  discard-paths: yes
