service: get-customer-api

provider:
  name: aws
  runtime: python3.11
  memorySize: 2000
  timeout: 30
  architecture: x86_64
  deploymentBucket:
    name: ramuslsbucket
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: arn:aws:dynamodb:us-east-1:*:table/*  # update with your account ID if needed

functions:
  getCustomer:
    handler: get_customers.lambda_handler
    events:
      - http:
          path: get-customer
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                id: true
                product: true


resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Customers
        AttributeDefinitions:
          - AttributeName: userid
            AttributeType: S
        KeySchema:
          - AttributeName: userid
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST  # On-demand pricing (no need for RCU/WCU)
        Tags:
          - Key: Environment
            Value: dev



package:
  patterns:
    - '!.git/**'
    - '!*.txt'
    - '!whizlabs_sls/**'
    - '!.serverless/**'