service: toggleec2
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  memorySize: 2000
  timeout: 30
  architecture: x86_64
  deploymentBucket:
    name: ramuslsbucket

  iam:
      role:
        name: toggle-ec2-lambda
        statements:
          # Allow functions to list all buckets
          - Effect: Allow
            Action: ["ec2:Describe*", "ec2:Get*", "ec2:StopInstances", "ec2:RunInstances", "ec2:TerminateInstances","ec2:StartInstances"]
            Resource: '*'

package:
  patterns:
    - '!.git/**'
    - '!*.txt'
    - '!whizlabs_sls/**'
    - '!.serverless/**'
    
functions:
  hello:
    handler: changeec2status.lambda_handler
    name: changeec2status-lambda-${sls:stage}
    description: Toggle the ec2 status
    events:
      - eventBridge:
          schedule: rate(2 minutes)


resources:
  Resources:
    EC2Instance:
      Type: AWS::EC2::Instance
      Properties:
        ImageId: ami-000ec6c25978d5999
        InstanceType: t2.micro
